import assert from 'node:assert/strict'
import { describe, it } from 'vitest'
import fixture from './fixtures/knowledge-projection-v2.json'
import { academicGraph, assembleKnowledgePages, loadCompleteKnowledgeGraph, loadKnowledgePage, notesFromPage, type KnowledgePage } from '../src/features/resources/academic-graph'
import { KNOWLEDGE_GRAPH_SCHEMA, KnowledgePageCollector, compareKnowledgeIDs, knowledgeProjectionDigest } from '../src/features/resources/knowledge-snapshot'

// Generated by Go TestProjectionUnicodeCrossLanguageFixture, not a TS response factory.
const pages = () => structuredClone(fixture) as KnowledgePage[]
const hash = 'sha256:' + 'a'.repeat(64)
const response = (data: unknown) => new Response(JSON.stringify({ data }), { headers: { 'Content-Type': 'application/json' } })

describe('academic knowledge snapshot consumption', () => {
  it('verifies Go pages, including non-BMP IDs, before rendering every assertion', async () => {
    const snapshot = await assembleKnowledgePages(pages())
    const graph = academicGraph(snapshot)
    assert.equal(snapshot.complete, true)
    assert.equal(graph.edges.length, 6)
    assert.equal(graph.edges.filter(edge => edge.self).length, 1)
    assert.equal(graph.nodes.filter(node => node.unresolved).length, 1)
    assert.deepEqual(notesFromPage(snapshot).map(note => note.path), ['memory/a.md', 'memory/\ue000.md', 'memory/😀.md'])
    assert.deepEqual(graph.nodes.map(node => node.degree), [5, 2, 3, 1])
  })

  it('rejects unfinished retrieval instead of exposing a partial library', async () => {
    await assert.rejects(assembleKnowledgePages([pages()[0]]), /not fully retrieved/)
    assert.throws(() => notesFromPage(pages()[0]), /incomplete/)
    assert.throws(() => academicGraph(pages()[0]), /Incomplete/)
  })

  it('rejects missing payloads and the retired array/v1 protocol', async () => {
    await assert.rejects(assembleKnowledgePages([]), /not fully retrieved/)
    const collector = new KnowledgePageCollector()
    assert.throws(() => collector.add([]), /unsupported/)
    assert.throws(() => collector.add({ ...pages()[0], schemaVersion: 'research.knowledge-graph/v1' }), /unsupported/)
  })

  it('accepts an explicitly complete empty graph with array fields', async () => {
    const empty: KnowledgePage = { schemaVersion: KNOWLEDGE_GRAPH_SCHEMA, snapshot: hash, queryId: hash, scope: 'knowledge', offset: 0,
      projectionDigest: await knowledgeProjectionDigest([], []), complete: true, counts: { nodes: 0, edges: 0, matched: 0, matchedEdges: 0, unresolved: 0, orphans: 0 }, nodes: [], edges: [] }
    assert.deepEqual((await assembleKnowledgePages([empty])).nodes, [])
    assert.throws(() => new KnowledgePageCollector().add({ ...empty, nodes: null }), /arrays/)
  })

  it('rejects mixed queries, snapshots, metadata and counts on any page', async () => {
    for (const change of [
      { queryId: hash }, { snapshot: hash }, { projectionDigest: hash }, { query: 'wrong' }, { scope: 'all' },
      { counts: { ...pages()[1].counts, matchedEdges: 5 } }, { offset: 3 },
    ]) {
      const data = pages(); Object.assign(data[1], change)
      await assert.rejects(assembleKnowledgePages(data))
    }
  })

  it('rejects missing edges even when every node is received', async () => {
    const data = pages(); data[0].edges.pop()
    await assert.rejects(assembleKnowledgePages(data), /incomplete node\/assertion set/)
  })

  it('rejects duplicate identities instead of replacing them in a Map', async () => {
    const duplicateNode = pages(); duplicateNode[1].nodes[0] = duplicateNode[0].nodes[0]
    await assert.rejects(assembleKnowledgePages(duplicateNode), /duplicate or unordered/)
    const duplicateEdge = pages(); duplicateEdge[0].edges[1] = duplicateEdge[0].edges[0]
    await assert.rejects(assembleKnowledgePages(duplicateEdge), /duplicate assertion/)
  })

  it('detects equal-count semantic corruption and wrong provenance', async () => {
    const data = pages(); data[0].nodes[0].title += ' corrupted'
    await assert.rejects(assembleKnowledgePages(data), /digest mismatch/)
    const provenance = pages(); provenance[0].edges[0].sourceRevision = hash
    await assert.rejects(assembleKnowledgePages(provenance), /source revision/)
    const endpoint = pages(); endpoint[0].edges.find(edge => !edge.self)!.target = 'absent'
    await assert.rejects(assembleKnowledgePages(endpoint), /endpoint/)
  })

  it('refuses missing successors, false terminal flags and extra pages', async () => {
    const missing = pages(); delete missing[0].nextCursor
    await assert.rejects(assembleKnowledgePages(missing), /successor/)
    const falseComplete = pages(); falseComplete[0].complete = true
    await assert.rejects(assembleKnowledgePages(falseComplete), /completeness/)
    const extra = pages(); extra.push(extra[1])
    await assert.rejects(assembleKnowledgePages(extra), /terminal page/)
  })

  it('stops cyclic cursors before making a third network request', async () => {
    const data = pages()
    for (const page of data) { page.counts.nodes = 6; page.counts.matched = 6 }
    data[1].nextCursor = data[0].nextCursor
    let calls = 0
    const original = globalThis.fetch
    globalThis.fetch = async () => {
      calls++
      if (calls > 3) throw new Error('test stopped a runaway paging loop')
      return response(data[Math.min(calls - 1, 1)])
    }
    try {
      await assert.rejects(loadCompleteKnowledgeGraph({ limit: 2 }), /cursor repeated/)
      assert.equal(calls, 2)
    } finally { globalThis.fetch = original }
  })

  it('loads a valid transport sequence with the same snapshot and exact cursors', async () => {
    const data = pages(), urls: string[] = []
    const original = globalThis.fetch
    globalThis.fetch = async input => { urls.push(String(input)); return response(data[urls.length - 1]) }
    try {
      const snapshot = await loadCompleteKnowledgeGraph({ limit: 2 })
      assert.equal(snapshot.edges.length, 6)
      const second = new URL(urls[1], 'https://example.invalid').searchParams
      assert.equal(second.get('snapshot'), data[0].snapshot)
      assert.equal(second.get('cursor'), data[0].nextCursor)
      assert.equal(second.get('limit'), '2')
    } finally { globalThis.fetch = original }
  })

  it('rejects an initial page returned for different filters or page size', async () => {
    const original = globalThis.fetch
    globalThis.fetch = async () => response(pages()[0])
    try {
      for (const change of [{ tags: ['control'] }, { direction: 'inbound' as const },
        { unresolved: 'exclude' as const }, { orphans: 'only' as const }, { limit: 1 }]) {
        await assert.rejects(loadKnowledgePage({ limit: 2, ...change }), /different query/)
      }
    } finally { globalThis.fetch = original }
  })

  it('propagates abort and transport failure without a complete result', async () => {
    const original = globalThis.fetch, controller = new AbortController()
    let calls = 0
    globalThis.fetch = async () => { calls++; controller.abort(); return response(pages()[0]) }
    try {
      await assert.rejects(loadCompleteKnowledgeGraph({ limit: 2 }, controller.signal), { name: 'AbortError' })
      assert.equal(calls, 1)
      globalThis.fetch = async () => { throw new Error('network unavailable') }
      await assert.rejects(loadCompleteKnowledgeGraph(), /network unavailable/)
    } finally { globalThis.fetch = original }
  })

  it('uses code-point ordering rather than locale or UTF-16 ordering', () => {
    assert.deepEqual(['😀', '\ue000', 'a'].sort(compareKnowledgeIDs), ['a', '\ue000', '😀'])
  })

  it('does not silently discard an edge if a consumer gives it a broken graph', async () => {
    const snapshot = await assembleKnowledgePages(pages())
    snapshot.nodes.pop()
    assert.throws(() => academicGraph(snapshot), /missing endpoint/)
  })
})
