export const writingCopy = {
  zh: {
    continueTitle: '继续写作',
    continueBody: '打开上次的项目，或从最近的研究项目进入论文工作台。',
    openLast: '继续上次项目',
    recent: '最近项目',
    allProjects: '全部项目',
    noProjects: '还没有可打开的研究项目。',
    genericChat: '不选项目，只打开通用对话',
    review: '设计审阅',
    reviewHint: '批注先进入讨论。确认当前设计与修改范围后，才由写作应用改正文。',
    openDesign: '打开设计',
    continueTalk: '继续讨论',
    confirmWrite: '确认并修改',
    collapseReview: '收起审阅',
    confirmUnavailable: '确认后改稿尚未接通。#128 的确认/应用 hook 合入前，这里不会执行正文写入。',
    previewLoading: '正在打开预览…',
    previewEmpty: '这份项目还没有成功编译的 PDF。保存当前稿件后由构建服务生成预览，不要求提交 Git。',
    previewUnavailable: '编译环境未就绪，不能把按钮当成已经能编译。',
    previewFailed: '无法读取构建记录。',
    openSource: '打开项目文件',
    openSettings: '打开设置',
    retryPreview: '重试预览',
    keepLast: '仍显示上次成功的 PDF；它尚未包含这次失败的修改。',
  },
  en: {
    continueTitle: 'Continue writing',
    continueBody: 'Resume the last project, or open a recent research project into the paper workbench.',
    openLast: 'Resume last project',
    recent: 'Recent projects',
    allProjects: 'All projects',
    noProjects: 'No research projects to open yet.',
    genericChat: 'Open a general chat without a project',
    review: 'Design review',
    reviewHint: 'Annotations join the discussion first. Source edits run only after the current design and scope are confirmed.',
    openDesign: 'Open design',
    continueTalk: 'Keep discussing',
    confirmWrite: 'Confirm and edit',
    collapseReview: 'Collapse review',
    confirmUnavailable: 'Confirmed source edits are not connected yet. This control will not write the manuscript until the #128 confirm/apply hook lands.',
    previewLoading: 'Opening preview…',
    previewEmpty: 'This project has no successful PDF yet. The build service compiles the saved manuscript; a Git commit is not required.',
    previewUnavailable: 'The compiler is not ready. A visible button is not a working build.',
    previewFailed: 'Build records could not be read.',
    openSource: 'Open project files',
    openSettings: 'Open settings',
    retryPreview: 'Retry preview',
    keepLast: 'The last successful PDF is still shown; it does not include this failed change.',
  },
} as const
