import {t as tr} from '../i18n'
import {useState} from 'react'
import {BookOpen, Folder, FolderOpen, MessageSquare, Network, PanelLeftClose, Settings, Workflow, Archive, Pencil, Check, ChevronRight} from 'lucide-react'
import {post,type Project} from '../lib/api'
import {NAV_ITEMS,useWorkbench} from '../store'
import {belongsToResearchScope,useNativeAgentSession} from '../features/chat/Session'
import {cn} from '../lib/cn'
import {Button,IconBtn,SearchTrigger} from './ui'
const item='flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-body transition-colors hover:bg-hover'
const icons={chat:MessageSquare,workflow:Workflow,graph:Network,knowledge:BookOpen,settings:Settings}
export function Sidebar({onCollapse,projects,onRefresh,loading,error}:{onCollapse:()=>void;projects:Project[];onRefresh:()=>void;loading:boolean;error:string}) {
 const {activeNav,setActiveNav,openChat,projectId,setProjectId,setPaletteOpen,setRightTab,setRightOpen}=useWorkbench();const native=useNativeAgentSession()
 const [renaming,setRenaming]=useState(''),[title,setTitle]=useState(''),[expanded,setExpanded]=useState<Record<string,boolean>>({}),[archived,setArchived]=useState(false)
 const [adding,setAdding]=useState(false),[name,setName]=useState(''),[busy,setBusy]=useState(false),[addError,setAddError]=useState('')
 const projectView=activeNav==='chat'||activeNav==='workflow'
 const newThread=(project:string)=>{setProjectId(project);native.newThread();setActiveNav('chat');setExpanded(s=>({...s,[project]:true}))}
 async function addProject(){setBusy(true);setAddError('');const id=`paper-${name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||crypto.randomUUID().slice(0,8)}`;try{await post('/workspaces',{workspaceId:id});await post('/research/projects',{schemaVersion:'xgc.research.protocol/v1',projectId:id,slug:id,title:name.trim(),summary:'',createdBy:'researcher',createdAt:new Date().toISOString()});setAdding(false);setName('');onRefresh();newThread(id)}catch(e){setAddError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function threads(project:string){const sessions=native.allSessions.filter(s=>belongsToResearchScope(s.scope,project,project,true)&&s.archived===archived);return <div className="ml-4 border-l border-line pl-1">{sessions.map(s=><div key={s.id} className={cn('group flex items-center rounded-md',native.selectedId===s.id&&'bg-active')}>
 {renaming===s.id?<form className="flex min-w-0 flex-1 p-1" onSubmit={e=>{e.preventDefault();void native.operation(async()=>{await native.updateThread(s.id,{title:title.trim()});setRenaming('')})}}><input aria-label={tr("线程名称")} required autoFocus className="ui-input min-w-0" value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setRenaming('')}}/><IconBtn icon={Check} label={tr("保存线程名称")} onClick={()=>void native.operation(async()=>{await native.updateThread(s.id,{title:title.trim()});setRenaming('')})}/></form>:<><button className={cn(item,'min-w-0 flex-1')} onClick={()=>native.selectProjectThread(project,s.id)}><MessageSquare size={12} className="shrink-0 text-ink-3"/><span className="truncate">{s.title||s.provider}</span></button><div className="flex opacity-0 focus-within:opacity-100 group-hover:opacity-100"><IconBtn icon={Pencil} label={`${tr("重命名")} ${s.title||s.provider}`} onClick={()=>{setRenaming(s.id);setTitle(s.title||'')}}/><IconBtn icon={Archive} label={archived?tr("恢复线程"):tr("归档线程")} onClick={()=>void native.operation(()=>native.updateThread(s.id,{archived:!s.archived}))}/></div></>}
 </div>)}<button className={cn(item,'text-ink-3')} onClick={()=>newThread(project)}>{tr("新线程")}</button></div>}
 return <div className="flex h-full w-full flex-col bg-panel">
 <div className="ui-toolbar border-b border-line"><div className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-accent text-[12px] font-bold text-accent-fg">A</div><span className="min-w-0 flex-1 truncate font-semibold">{tr("Atlas Research")}</span><IconBtn icon={PanelLeftClose} label={tr("收起侧栏")} onClick={onCollapse}/></div>
 <div className="px-3 pt-2"><SearchTrigger placeholder={tr("查找…")} shortcut="⌘K" onClick={()=>setPaletteOpen(true)} className="w-full"/></div>
 <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-3"><nav aria-label={tr("主导航")} className="mt-3 space-y-px">{NAV_ITEMS.filter(n=>n.id!=='settings').map(n=>{const Icon=icons[n.id],active=activeNav===n.id&&(n.id!=='chat'||!projectId);return <div key={n.id}><button aria-current={active?'page':undefined} onClick={()=>{if(n.id==='chat'){openChat();setExpanded(s=>({...s,'':true}))}else setActiveNav(n.id)}} className={cn(item,active?'bg-active font-medium text-ink':'text-ink-2')}><Icon size={15} className="shrink-0 text-ink-3"/>{tr(n.label)}</button>{n.id==='chat'&&(expanded['']??!projectId)&&threads('')}</div>})}</nav>
 <div className="mt-5 flex h-7 items-center justify-between px-2"><span className="text-caption font-semibold text-ink-3">{tr("PROJECTS")}</span><button className="text-caption text-ink-2 hover:text-ink" onClick={()=>setAdding(s=>!s)}>{tr("添加项目")}</button></div>
 {adding&&<form className="space-y-2 rounded-md border border-line p-2" onSubmit={e=>{e.preventDefault();void addProject()}}><input required autoFocus aria-label={tr("项目名称")} placeholder={tr("项目名称")} className="ui-input" value={name} onChange={e=>setName(e.target.value)}/><Button type="submit" variant="solid" loading={busy}>{tr("创建项目")}</Button><Button disabled={busy} onClick={()=>setAdding(false)}>{tr("取消")}</Button>{addError&&<p role="alert" className="text-caption">{addError}</p>}</form>}
 {error&&<p className="ui-error" role="alert">{error}</p>}
 {projects.map(p=>{const open=expanded[p.id]??projectId===p.id;return <section key={p.id} aria-label={`${tr("项目")} ${p.title}`}><div className={cn('group flex items-center rounded-md',projectView&&projectId===p.id&&'bg-active')}><button aria-label={`${open?tr('收起'):tr('展开')} ${p.title}`} aria-expanded={open} className="shrink-0 p-1 text-ink-3" onClick={()=>setExpanded(s=>({...s,[p.id]:!open}))}><ChevronRight size={12} className={open?'rotate-90':''}/></button><button className={cn(item,'min-w-0 flex-1',projectView&&projectId===p.id?'font-medium':'text-ink-2')} title={p.title} onClick={()=>{setProjectId(p.id);setActiveNav('chat');setExpanded(s=>({...s,[p.id]:true}))}}><Folder size={14} className="shrink-0 text-ink-3"/><span className="truncate">{p.title}</span></button><IconBtn icon={FolderOpen} label={`${tr("项目文件")} · ${p.title}`} onClick={()=>{setProjectId(p.id);setExpanded(s=>({...s,[p.id]:true}));setRightTab("files");setRightOpen(true)}}/></div>{open&&threads(p.id)}</section>})}
 {loading&&!projects.length&&<p className="px-2 py-2 text-caption text-ink-3">{tr("正在读取项目…")}</p>}
 <button className="mt-3 px-2 text-caption text-ink-3" onClick={()=>setArchived(!archived)}>{archived?tr("隐藏已归档线程"):tr("显示已归档线程")}</button>
 </div><div className="border-t border-line p-2"><button className={cn(item,activeNav==='settings'&&'bg-active')} onClick={()=>setActiveNav('settings')}><Settings size={15}/>{tr("设置")}</button></div>
 </div>
}
