export const projectObjectCopy = {
  zh: {
    objects: '项目对象', files: '项目材料', notes: '项目内笔记', builds: '已构建 PDF',
    canvas: '研究画布', workflow: '项目工作流', back: '返回项目', parent: '上级目录',
    backToFiles: '返回对象列表', refresh: '重新读取', loading: '正在读取…',
    selectProject: '从项目侧栏打开材料；这个空标签不会随项目切换。',
    noFiles: '此目录没有研究资料。', noNotes: '此目录没有 Markdown 笔记；可继续打开子目录查找。',
    noBuilds: '这个项目还没有成功构建的 PDF。请从 LaTeX 源稿编译；外部论文不属于构建记录。',
    unsupported: '此附件暂不支持内嵌预览；保留原文件，不推断为可编辑制品。',
    scope: '项目', storage: '工作区文件', version: '文件版本', readOnly: '只读',
    noteScope: '仅筛选项目工作区的 Markdown 文件，不代表已关联的全局知识。',
    build: '构建', source: '当前源稿', quote: '引用到 Chat', compile: '编译 PDF',
    showPDF: '查看 PDF', noPDF: '此稿件还没有已编译的 PDF。',
    canvasLoading: '正在读取画布…', canvasNew: '尚未创建，编辑后保存',
    canvasSaving: '保存中…', canvasUnsaved: '尚未保存',
    canvasLoadError: '无法读取画布，未创建空白文件。',
    canvasInvalid: '画布格式无法安全编辑，原文件未改动。',
    canvasSaveError: '保存失败，本地修改仍保留。',
    canvasConflict: '远端文件已变化，本地修改未覆盖远端。',
    retrySave: '重试保存', reloadCanvas: '重新读取画布',
    discardReload: '丢弃本地并重读', discardConfirm: '丢弃未保存的本地画布修改并重新读取远端？',
    exportDraft: '导出本地副本',
  },
  en: {
    objects: 'Project objects', files: 'Project materials', notes: 'Project notes', builds: 'Built PDFs',
    canvas: 'Research canvas', workflow: 'Project workflow', back: 'Back to project', parent: 'Parent directory',
    backToFiles: 'Back to objects', refresh: 'Reload', loading: 'Loading…',
    selectProject: 'Open materials from a project in the sidebar. This empty tab does not follow project selection.',
    noFiles: 'No research materials in this directory.', noNotes: 'No Markdown notes here. Open a subdirectory to look further.',
    noBuilds: 'No successful PDF builds for this project. Compile a LaTeX source first; imported papers are not build records.',
    unsupported: 'Inline preview is not available for this attachment. The original file is retained, not treated as an editable artifact.',
    scope: 'Project', storage: 'Workspace file', version: 'File revision', readOnly: 'Read only',
    noteScope: 'Markdown files in this project workspace only, not a list of linked global knowledge.',
    build: 'Build', source: 'Current source', quote: 'Quote to Chat', compile: 'Compile PDF',
    showPDF: 'View PDF', noPDF: 'This manuscript has no compiled PDF yet.',
    canvasLoading: 'Loading canvas…', canvasNew: 'Not created yet; saved after editing',
    canvasSaving: 'Saving…', canvasUnsaved: 'Not saved yet',
    canvasLoadError: 'Could not read the canvas. No empty file was created.',
    canvasInvalid: 'This canvas cannot be safely edited. The original file is unchanged.',
    canvasSaveError: 'Save failed. Local edits are retained.',
    canvasConflict: 'The remote file changed. Local edits have not overwritten it.',
    retrySave: 'Retry save', reloadCanvas: 'Reload canvas',
    discardReload: 'Discard local edits and reload', discardConfirm: 'Discard unsaved local canvas edits and reload the remote file?',
    exportDraft: 'Export local copy',
  },
} as const
