export const workspaceCopy = {
  zh: {
    more: '画布操作', canvas: '研究画布', chat: '对话', split: '并排', focusCanvas: '画布',
    layout: '研究工作区布局', close: '收起画布', files: '打开资料',
    divider: '调整对话与画布宽度',
    narrow: '当前工作区宽度不足；收起侧栏或右栏后可并排。',
    copyFailed: '复制失败，请重试。', saveFailed: '保存失败；修改仍在当前页面中。',
    addToDraft: '加入对话草稿', fit: '适应画布',
    outline: '大纲', undo: '撤销', redo: '重做',
    locateCanvas: '在画布中定位', locateOutline: '在大纲中定位',
    unarranged: '未编排想法', arrange: '加入大纲', removeFromOutline: '移出大纲',
    indent: '增加层级', outdent: '减少层级', collapsed: '折叠或展开',
    moveUp: '上移', moveDown: '下移',
    relation: '语义关系', plainRelation: '未标注 · 普通关联',
    relationSupports: '支持', relationContradicts: '反驳', relationDepends: '依赖',
    relationExemplifies: '举例', relationContinues: '承接', relationCites: '引用',
    relationHint: '未标注的连线只是普通关联，不代表因果或执行顺序。',
    evidence: '证据', addEvidence: '添加证据', evidencePath: '证据文件路径',
    evidenceDigest: '观察到的版本（可空）', evidenceExcerpt: '摘录（可空）', evidenceNote: '来源备注（可空）',
    unverifiable: '无法自动校验版本', locateSource: '定位来源', invalidEvidence: '需要有效的相对文件路径或 HTTP(S) 地址。',
    writingConstraints: '写作意图', purpose: '写作目的', argument: '论证安排', conditions: '适用条件',
    template: '模板要求', omission: '详略（不得写入正文）', aside: '正文外细节（不得写入正文）',
    sourceBindings: '对应正文', bindFromSource: '在源码中选区后绑定', noBindings: '尚未绑定正文选区。',
    locateBinding: '定位正文', removeBinding: '解除对应', bindingUncertain: '需要校正，未按旧行号重绑。',
    insertWritingContext: '插入本次写作上下文', captureBlocked: '画布未保存或有冲突，不能作为可应用基线。',
    relatedDesign: '相关设计', bindToFocus: '绑定到当前设计卡', noDesignFocus: '先在画布选中一张设计卡。',
    confirmBinding: '确认这张卡', designCandidates: '候选设计，需人工校正。',
    deleteEdge: '删除连线',
    addToContext: '加入 Chat 上下文', arrangement: '制品编排', primaryOutline: '画布大纲',
    newArrangement: '建立制品编排', arrangementHint: '制品只保留编排顺序；正文仍在研究对象里编辑。',
  },
  en: {
    more: 'Canvas actions', canvas: 'Research canvas', chat: 'Chat', split: 'Split', focusCanvas: 'Canvas',
    layout: 'Research workspace layout', close: 'Hide canvas', files: 'Open materials',
    divider: 'Resize chat and canvas',
    narrow: 'Not enough workspace width. Collapse a side panel to use split view.',
    copyFailed: 'Copy failed. Please try again.', saveFailed: 'Save failed; changes remain in this page.',
    addToDraft: 'Add to chat draft', fit: 'Fit canvas',
    outline: 'Outline', undo: 'Undo', redo: 'Redo',
    locateCanvas: 'Locate on canvas', locateOutline: 'Locate in outline',
    unarranged: 'Unarranged ideas', arrange: 'Add to outline', removeFromOutline: 'Remove from outline',
    indent: 'Indent', outdent: 'Outdent', collapsed: 'Collapse or expand',
    moveUp: 'Move up', moveDown: 'Move down',
    relation: 'Semantic relation', plainRelation: 'Unlabeled · plain association',
    relationSupports: 'supports', relationContradicts: 'contradicts', relationDepends: 'depends on',
    relationExemplifies: 'exemplifies', relationContinues: 'continues', relationCites: 'cites',
    relationHint: 'An unlabeled link is a plain association, never causality or execution order.',
    evidence: 'Evidence', addEvidence: 'Add evidence', evidencePath: 'Evidence file path',
    evidenceDigest: 'Observed revision (optional)', evidenceExcerpt: 'Excerpt (optional)', evidenceNote: 'Source note (optional)',
    unverifiable: 'Version cannot be auto-verified', locateSource: 'Locate source', invalidEvidence: 'A valid relative file path or HTTP(S) URL is required.',
    writingConstraints: 'Writing intent', purpose: 'Writing purpose', argument: 'Argument plan', conditions: 'Applicability conditions',
    template: 'Template requirements', omission: 'Scope (do not copy into the manuscript)', aside: 'Off-manuscript detail (do not copy into the manuscript)',
    sourceBindings: 'Mapped source', bindFromSource: 'Bind after selecting source text', noBindings: 'No source range is bound yet.',
    locateBinding: 'Locate source', removeBinding: 'Remove mapping', bindingUncertain: 'Needs correction; old line numbers were not reused.',
    insertWritingContext: 'Insert this writing context', captureBlocked: 'Unsaved or conflicted canvas cannot be an apply baseline.',
    relatedDesign: 'Related design', bindToFocus: 'Bind to the focused design card', noDesignFocus: 'Select a design card on the canvas first.',
    confirmBinding: 'Confirm this card', designCandidates: 'Candidate designs; confirm one.',
    deleteEdge: 'Delete link',
    addToContext: 'Add to Chat context', arrangement: 'Artifact arrangement', primaryOutline: 'Canvas outline',
    newArrangement: 'Create artifact arrangement', arrangementHint: 'An arrangement only orders shared cards; the body stays in the research object.',
  },
} as const
