import {
  ArrowLeftRight,
  Archive,
  Bell,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Cable,
  CalendarClock,
  Camera,
  ClockCheck,
  Crosshair,
  Cuboid,
  Database,
  FileCode2,
  FileOutput,
  FlaskConical,
  FormInput,
  Gamepad2,
  GitBranch,
  LayoutDashboard,
  MessageCircle,
  MessageSquareText,
  Monitor,
  MonitorPlay,
  Move3d,
  MousePointerClick,
  Network,
  PanelTopOpen,
  PanelsTopLeft,
  Plane,
  Plug,
  Radar,
  RadioTower,
  Rocket,
  Save,
  ScanLine,
  Send,
  ServerCog,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquareStop,
  TerminalSquare,
  Trash2,
  Waypoints,
  Webhook,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import {
  automationNodeIconFromComposition,
  type AutomationNodeWebComposition,
} from './nodes/automationNodeWebComposition';

/**
 * Generic-shell icon fallbacks for kinds not yet owned by an exclusive leaf.
 * Leaf-owned icons resolve only through AutomationNodeWebComposition.
 */
const NODE_KIND_ICONS: Record<string,LucideIcon> = {
  'trigger.schedule': CalendarClock,
  'trigger.target-startup': Rocket,
  'trigger.form-submission': FormInput,
  'trigger.chat-message': MessageCircle,
  'trigger.webhook': Webhook,
  'asset.experiment-robots': Bot,
  'robot.operation': Gamepad2,
  'robot.ensure-connected': Cable,
  'experiment.session.materialize-clock-policy': ClockCheck,
  'experiment.session.run-clock-guard': ShieldCheck,
  'experiment.panel.exists': PanelTopOpen,
  'calibration.commit': Save,
  'calibration.render-file': FileOutput,
  'user.script': FileCode2,
  'mcp.tool.call': Wrench,
  'mcp.resource.read': BookOpen,
  'mcp.prompt.get': MessageSquareText,
  'panel.state.get': PanelTopOpen,
  'simulation.render-fs150-sdf': FileOutput,
  'simulation.spawn-fs150-sdf': Bot,
  'simulation.gazebo-spawn-obstacle': Cuboid,
  'simulation.gazebo-move-obstacle': Move3d,
  'simulation.gazebo-clear-obstacles': Trash2,
  'simulation.gazebo-configure-obstacle-motion': SlidersHorizontal,
  'simulation.gazebo-stop-obstacle-motion': SquareStop,
  'visualization.robot-scene': MonitorPlay,
  'visualization.robot-descriptions': Bot,
  'visualization.lichtblick-layout': LayoutDashboard,
  'ros1.wait-roscore-ready': Network,
  'ros1.wait-gazebo-ready': Box,
  'ros1.publish-topic': Send,
  'ros1.call-service': ArrowLeftRight,
  'ros1.record-bag': Archive,
  'ros1.run': TerminalSquare,
  'ros2.publish-topic': Send,
  'ros2.call-service': ArrowLeftRight,
  'ros2.run': TerminalSquare,
  'ros2.launch': Rocket,
  'process-preset:lichtblick-web': MonitorPlay,
  'process-preset:roscore': Network,
  'process-preset:foxglove-bridge': Cable,
  'process-preset:gazebo-server': Box,
  'process-preset:scout-gazebo-robot': Bot,
  'process-preset:mavros-px4-sitl': Plane,
  'process-preset:gazebo-vrpn-server': Radar,
  'process-preset:vrpn-client-ros1': Crosshair,
  'process-preset:rviz': Monitor,
  'process-preset:px4-sitl-fs150': Plane,
  'process-preset:gazebo-client': Monitor,
  'process-preset:xgc2-camera-intrinsic-calibrator-ros1': ScanLine,
  'process-preset:xgc2-camera-extrinsic-calibrator-ros1': Crosshair,
  'process-preset:xgc2-camera-extrinsic-tf-ros1': Waypoints,
};

const NODE_CATEGORY_ICONS: Record<string,LucideIcon> = {
  trigger: MousePointerClick,
  process: ServerCog,
  adapter: Plug,
  control: GitBranch,
  automation: Workflow,
  action: Rocket,
  ros1: RadioTower,
  ros2: RadioTower,
  robot: Bot,
  asset: Bot,
  data: Database,
  experiment: FlaskConical,
  calibration: SlidersHorizontal,
  mcp: Wrench,
  'user-scripts': FileCode2,
  usernode: FileCode2,
  simulation: Boxes,
  visualization: MonitorPlay,
  advanced: TerminalSquare,
  parameter: Database,
  perception: Camera,
  // Product leaves such as Media supply icons via AutomationNodeWebComposition;
  // the generic host must not hardcode Media category chrome.
  panel: PanelsTopLeft,
  'ground-station': Bell,
  other: Sparkles,
};

export function automationNodeIcon(
  kind: string,
  category: string,
  typeVersion = 0,
  nodeComposition?: AutomationNodeWebComposition,
) {
  return automationNodeIconFromComposition(nodeComposition, kind, typeVersion)
    ?? NODE_KIND_ICONS[kind]
    ?? NODE_CATEGORY_ICONS[category]
    ?? Workflow;
}

export function automationNodeCategory(category?: string) {
  return category?.trim().toLowerCase().replace(/[^a-z0-9_-]+/g, '-') || 'other';
}
