// Code generated by scripts/generate-workflow-control-contract.py. DO NOT EDIT.

export const WORKFLOW_CONTROL_MANIFEST_VERSION = 1;
export const WORKFLOW_CONTROL_MANIFEST_DIGEST = "a777347fd3c30a6da47010f853f06020ea0d451e42df319ebf70ecb1dd798103";
export const AUTOMATION_SCHEMA_VERSION = 4;
export const EXPERIMENT_SCHEMA_VERSION = 15;
export const PANEL_SCHEMA_VERSION = 4;

export const WORKFLOW_ACTION_KINDS = ["command","control-stream","interaction","service"] as const;
export type WorkflowActionKind = typeof WORKFLOW_ACTION_KINDS[number];
export const WORKFLOW_ACTION_CONTROLS = ["cancel","restart","signal","stop"] as const;
export type WorkflowActionControl = typeof WORKFLOW_ACTION_CONTROLS[number];
export const PANEL_PORT_KINDS = ["action","authoring","data","interaction","workflow"] as const;
export type PanelPortKind = typeof PANEL_PORT_KINDS[number];
export const INVOCATION_SOURCES = ["api","manual","panel","schedule","startup","webhook","workflow-call"] as const;
export type InvocationSource = typeof INVOCATION_SOURCES[number];
