// Code generated by scripts/generate-workflow-control-contract.py. DO NOT EDIT.

export const WORKFLOW_CONTROL_MANIFEST_VERSION = 1;
export const WORKFLOW_CONTROL_MANIFEST_DIGEST = "73eb9386e0e48537d1e502e15b934c952bb2b9377265d4f67fbcd624f783ecbf";
export const AUTOMATION_SCHEMA_VERSION = 4;
export const EXPERIMENT_SCHEMA_VERSION = 16;
export const PANEL_SCHEMA_VERSION = 4;

export const WORKFLOW_ACTION_KINDS = ["command","control-stream","interaction","service"] as const;
export type WorkflowActionKind = typeof WORKFLOW_ACTION_KINDS[number];
export const WORKFLOW_ACTION_CONTROLS = ["cancel","restart","signal","stop"] as const;
export type WorkflowActionControl = typeof WORKFLOW_ACTION_CONTROLS[number];
export const PANEL_PORT_KINDS = ["action","authoring","data","interaction","workflow"] as const;
export type PanelPortKind = typeof PANEL_PORT_KINDS[number];
export const INVOCATION_SOURCES = ["api","manual","panel","schedule","startup","webhook","workflow-call"] as const;
export type InvocationSource = typeof INVOCATION_SOURCES[number];
